pull_request_rules:
  - name: chain-g1
    conditions:
      - label=ssti-test
    actions:
      comment:
        message: |
          JOINER={{joiner()|string}}
          NS={{namespace()|string}}
          DICT={{dict(a=1,b=2)}}
          ITEMS={% for k,v in dict(x=lipsum,y=cycler).items() %}{{k}}={{v|string|truncate(60)}},{% endfor %}
