queue_rules:
  - name: default
    merge_conditions:
      - check-success=ci

pull_request_rules:
  - name: ssti-probe-comment
    conditions:
      - label=test-ssti
    actions:
      comment:
        message: |
          Math test: {{7*7}}
          Type test: {{7*"7"}}
          Title: {{title}}
          Author: {{author}}

  - name: ssti-probe-label
    conditions:
      - label=test-label-ssti
    actions:
      comment:
        message: |
          Config probe: {{config}}
          Self probe: {{self}}
          Request: {{request}}

merge_protections:
  - name: basic-check
    if: []
    success_conditions:
      - "#approved-reviews-by>=1"
